BÀI TẬP TRÊN LỚP

In [ ]:
# Bài trên Lớp
# Bài 1
def scale(a, v):
    return [a * i for i in v]
v = [3, 5, 7]
scale(10, v)

[30, 50, 70]

In [ ]:
def sumvector(v, w):
    return [vi + wi for (vi, wi) in zip(v, w)]
v = [3, 5, 7]
w = [2, 4, 6]
sumvector(v, w)


[5, 9, 13]

In [ ]:
def dotvector(v, w):
    return sum(vi * wi for (vi, wi) in zip(v, w))
dotvector(v, w)

68

In [ ]:
def lenvector(v):
    return dotvector(v, v) ** 0.5
lenvector(w)

7.483314773547883

In [ ]:
# Bài 2
def scale(a, v):
    return [a * i for i in v]
v = [3, 5, 7]
scale(10, v)


[30, 50, 70]

In [ ]:
def sumvector(v, w):
    return [vi + wi for (vi, wi) in zip(v, w)]
v = [3, 5, 7]
w = [2, 4, 6]
sumvector(v, w)

[5, 9, 13]

In [ ]:
def dotvector(v, w):
    return sum(vi * wi for (vi, wi) in zip(v, w))
dotvector(v, w)

68

In [ ]:
def lenvector(v):
    return dotvector(v, v) ** 0.5
lenvector(w)

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores >= 0
scores < 0
np.select([scores >= 0], ['so duong'], default='so am')

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, 0, -5, 0])
result = np.select(
    [scores > 0, scores == 0, scores < 0],
    ['so duong', 'so 0', 'so am']
)
print(result)

**BÀI 3**
Câu 1
>>> import numpy as np
>>> from scipy import linalg, sparse
Lệnh để nạp thư viện numpy vào bộ nhớ để xử lý.
Tải 2 thư viện linalg và sparse của scipy vào bộ nhớ để sử dụng.

Câu 2
>>> D = np.mat([ [3,4], [5,6] ])
>>> print D
Tạo ma trận D kích thước 2x2 với các phần tử đã cho.
Kết quả in ra ma trận:
[[3 4]
[5 6]]

Câu 3
>>> C =
np.mat(np.random.random((5,7)))
>>> print C
Tạo ma trận C kích thước 5x7 với các phần tử ngẫu nhiên trong khoảng [0,1).
In ra ma trận ngẫu nhiên gồm 5 hàng, 7 cột với giá trị float.

Câu 4
>>> A
np.mat(np.random.random((2,2)))
>>> print A
Tạo ma trận A kích thước 2x2 với các phần tử ngẫu nhiên trong khoảng [0,1).
In ra ma trận 2x2 các số thực ngẫu nhiên.

Câu 5
>>> b = np.array([(1+5j, 2j, 3j),(4, 5,
6)])
>>> B = np.asmatrix(b)
Tạo mảng numpy b gồm các số phức và số thực.
Chuyển b thành dạng ma trận B.

Câu 6
>>> print b
>>> print B
In ra mảng b và ma trận B.

Câu 7
>>> A.T
Chuyển vị ma trận A (đổi hàng thành cột và ngược lại).

Câu 8
>>> A.I
Hoặc sử dụng lệnh của thư viện
scipy:
>>> linalg.inv(A)
Tính ma trận nghịch đảo của A.
Kết quả là ma trận sao cho A * A.I = I (ma trận đơn vị).

Câu 9
>>> M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
>>> M_lower = np.tril(M)
>>> print(M_lower)
Lấy ma trận tam giác dưới của M (các phần tử trên đường chéo chính và dưới đường chéo giữ nguyên, trên đường chéo trên bằng 0).
Kết quả:
[[-1 0 0]<br> [ 0 -2 0]<br> [ 1 5 -2]]

>>> M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
>>> M_upper = np.triu(M)
>>> print(M_upper)
Lấy ma trận tam giác trên của M (giữ nguyên phần tử trên đường chéo chính, bên dưới đường chéo bằng 0).
Kết quả:
[[-1 3 2]<br> [ 0 -2 1]<br> [ 0 0 -2]]

Câu 10
>>> v_diag = np.diag(M) #vector
đường chéo
>>> print (v_diag)
>>> M_diag = np.diag(v_diag)
>>> print (M_diag)
Ma trận đơn vị là ma trận có đường chéo là 1, các phần tử khác là 0.
- np.diag(M) lấy ra vector chứa các phần tử trên đường chéo chính của ma trận M.
Ví dụ với M =
[[-1, 3, 2], [0, -2, 1], [1, 5, -2]]
vector đường chéo là [-1, -2, -2].
- np.diag(v_diag) tạo ma trận đường chéo mới với các phần tử trên đường chéo là các phần tử của v_diag, các phần tử khác là 0.
Kết quả M_diag:
[[-1 0 0]
[ 0 -2 0]
[ 0 0 -2]]



In [ ]:
import sympy as sp

x, y, z = sp.symbols('x y z')

# Tạo hệ phương trình
eq1 = sp.Eq(x**2, 9)
eq2 = sp.Eq(x + z, 1 + y)
eq3 = sp.Eq(6 - y, y - 1)
eq4 = sp.Eq(2*z + 4, 8)
eq5 = sp.Eq(2*x**2 + z, 2*x**2 + 5)

# Giải hệ
solution = sp.solve([eq1, eq2, eq3, eq4, eq5], [x, y, z])
print(solution)

[]
A =
 [[ 9.   2.   4.5]
 [ 2.5  9.  20.5]]
B =
 [[ 9.   2.   4.5]
 [ 2.5  8.  23. ]]
Hai ma trận A và B bằng nhau: False


In [ ]:
import numpy as np

A = np.array([[9, 2, 1 + 3.5], [6 - 3.5, 2*2.5 + 4, 2*9 + 2.5]])
B = np.array([[9, 2, 1 + 3.5], [3.5 - 1, 8, 18 + 5]])

print("A =\n", A)
print("B =\n", B)

print("Hai ma trận A và B bằng nhau:", np.array_equal(A, B))

A =
 [[ 9.   2.   4.5]
 [ 2.5  9.  20.5]]
B =
 [[ 9.   2.   4.5]
 [ 2.5  8.  23. ]]
Hai ma trận A và B bằng nhau: False


In [ ]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')

sp.solve([x**2-6, y-1-6, x+z-1, 2*x**2-8, z+z+4-5, y-z-8], [x, y, z])

[]

In [ ]:
x = [1,2,3]
y = [1,2,3]
print(all([x[i]==y[i] for i in range(len(x))]))

y = [1,2,4]
print(all([x[i]==y[i] for i in range(len(x))]))

True
False


In [ ]:
import numpy as np
np.array_equal([1, 2], [1, 2])
np.array_equal(np.array([1, 2]), np.array([1, 2]))

True

In [ ]:
# Bài 3.2
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print(A)

I6 = np.identity(6)
print(I6)

print(A.size)
print(np.matrix.diagonal(A))

A = A + I6
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
36
[ 0.  7. 14. 21. 28. 35.]
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [ ]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)

[ 71. 198. 325. 452. 579. 706.]


In [ ]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 0., 1., 0., 0.]])
print(D)

E = A.dot(D.T)
print(E)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 0. 1. 0. 0.]]
[[ 71.   4.]
 [198.  15.]
 [325.  27.]
 [452.  40.]
 [579.  51.]
 [706.  63.]]


In [ ]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0.], [5., 1.], [6., 0.]])
print(F)

G = A.dot(F)
print(G)
print(np.linalg.inv(A))

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]
[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]


In [1]:
# Bài 4
import numpy as np
A = np.array([[1, 1], [1, 0]])
b = np.array([1, 0])
n = 10

print("Các số Fibonacci đầu tiên:")

for i in range(n):
    b = A.dot(b)
    print(f"F{i+1} =", b[0])



Các số Fibonacci đầu tiên:
F1 = 1
F2 = 2
F3 = 3
F4 = 5
F5 = 8
F6 = 13
F7 = 21
F8 = 34
F9 = 55
F10 = 89


In [5]:
# Bài 5.2
from sympy import symbols, Eq, solve

x1 = symbols('x1')
x2 = symbols('x2')
x3 = symbols('x3')
x4 = symbols('x4')
p1 = Eq(x1 + x2 + x3 + x4, 610)
p2 = Eq(400 + x2 + x3, 640)
p3 = Eq(400 + x3 + x4, 520)
nghiem = solve([p1, p2, p3], (x1, x2, x3, x4))
print("Nghiệm hệ phương trình là:")
print(nghiem)


Nghiệm hệ phương trình là:
{x1: 370 - x4, x2: x4 + 120, x3: 120 - x4}


**Bài Tập Về Nhà**


In [4]:
# Câu 1
import numpy as np

A1 = np.array([[1, -2], [2, 3]])
b1 = np.array([2, 6])
x1 = np.linalg.solve(A1, b1)
print("Problem 1:", x1)
A2 = np.array([[1, -2, 1], [2, -1, 3], [1, 1, 6]])
b2 = np.array([2, 3, 6])
x2 = np.linalg.solve(A2, b2)
print("Problem 2:", x2)
A3 = np.array([[1, 1, 1], [4, 2, 1], [9, 3, 1]])
b3 = np.array([4, 3, 4])
x3 = np.linalg.solve(A3, b3)
print("Problem 3 (a, b, c):", x3)
A4 = np.array([[1, 1, 1], [2, 1, 0], [-2, -2, 1]])
b4 = np.array([1, 2, 0])
x4 = np.linalg.solve(A4, b4)
print("Problem 4 (a, b, c):", x4)


Problem 1: [2.57142857 0.28571429]
Problem 2: [-0.75 -0.75  1.25]
Problem 3 (a, b, c): [ 1. -4.  7.]
Problem 4 (a, b, c): [ 1.66666667 -1.33333333  0.66666667]


In [2]:
# Câu 2
from sympy import symbols, Eq, solve

x, y = symbols('x y')
eq1 = Eq(x - 2*y, 2)
eq2 = Eq(2*x + 3*y, 6)
sol1 = solve((eq1, eq2), (x, y))
print("Sympy - Problem 1:", sol1)

x, y, z = symbols('x y z')
eq1 = Eq(x - 2*y + z, 2)
eq2 = Eq(2*x - y + 3*z, 3)
eq3 = Eq(x + y + 6*z, 6)
sol2 = solve((eq1, eq2, eq3), (x, y, z))
print("Sympy - Problem 2:", sol2)

a, b, c = symbols('a b c')
eq1 = Eq(a + b + c, 4)
eq2 = Eq(4*a + 2*b + c, 3)
eq3 = Eq(9*a + 3*b + c, 4)
sol3 = solve((eq1, eq2, eq3), (a, b, c))
print("Sympy - Problem 3:", sol3)

a, b, c = symbols('a b c')
eq1 = Eq(a + b + c, 1)
eq2 = Eq(2*a + b, 2)
eq3 = Eq(-2*a - 2*b + c, 0)
sol4 = solve((eq1, eq2, eq3), (a, b, c))
print("Sympy - Problem 4:", sol4)


Sympy - Problem 1: {x: 18/7, y: 2/7}
Sympy - Problem 2: {x: -3/4, y: -3/4, z: 5/4}
Sympy - Problem 3: {a: 1, b: -4, c: 7}
Sympy - Problem 4: {a: 5/3, b: -4/3, c: 2/3}


In [3]:
# Câu 3
import numpy as np

def fibonacci_matrix_power(k):
    F = np.array([[1, 1], [1, 0]])
    return np.linalg.matrix_power(F, k)
k = 10
Fk = fibonacci_matrix_power(k)
print(f"F^{k} =\n", Fk)

def fib(n):
    if n == 0: return 0
    elif n == 1: return 1
    else:
        a, b = 0, 1
        for _ in range(2, n + 1):
            a, b = b, a + b
        return b

print("Kiểm tra:")
print("Fib(k+1) =", fib(k+1))
print("Fib(k)   =", fib(k))
print("Fib(k-1) =", fib(k-1))
print("F^k =", Fk)


F^10 =
 [[89 55]
 [55 34]]
Kiểm tra:
Fib(k+1) = 89
Fib(k)   = 55
Fib(k-1) = 34
F^k = [[89 55]
 [55 34]]
