In [3]:
import numpy as np
from math import acos, degrees


A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])

# a) Tính tổng A + B và tích số 3A − 2B.
print("a)")
print("A + B =", A + B)
print("3A - 2B =", 3*A - 2*B)

# b) Tính tích vô hướng A · B và góc giữa hai vector (tính bằng độ, làm tròn đến 3 chữ số thập phân)
dot = A @ B
cos = dot / (np.linalg.norm(A) * np.linalg.norm(B))
angle = degrees(acos(cos))

print("\nb)")
print("A · B =", dot)
print("Góc (độ) =", round(angle, 3))

# c) Tính tích ma trận C
print("\nc)")
print("Cᵀ · C =\n", C.T @ C)



a)
A + B = [3 3 1 5]
3A - 2B = [  4 -11  13 -10]

b)
A · B = -8
Góc (độ) = 108.376

c)
Cᵀ · C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]
