In [ ]:
import numpy as np

P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])
b = np.array([4, 7, 9, 5])
P_inv = np.linalg.inv(P)
x = P_inv @ b
kiem_tra = P @ x
print("a) Ma trận nghịch đảo P⁻¹:\n", np.round(P_inv, 3))
print("\nb) Nghiệm x của hệ phương trình:\n", np.round(x, 3))
print("\nc) Kiểm tra lại P · x:\n", np.round(kiem_tra, 3))


a) Ma trận nghịch đảo P⁻¹:
 [[ 0.488 -0.093  0.023 -0.209]
 [ 0.035  0.279 -0.07   0.128]
 [-0.116  0.07   0.233 -0.093]
 [-0.012 -0.093  0.023  0.291]]

b) Nghiệm x của hệ phương trình:
 [0.465 2.105 1.651 0.965]

c) Kiểm tra lại P · x:
 [4. 7. 9. 5.]
