In [1]:
import numpy as np

M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

# a) Tính tích ma trận M × N
print("a) M × N =\n", M @ N)

# b) Tính định thức của ma trận M
print("\nb) Định thức M =", round(np.linalg.det(M), 3))

# c)  Tính hạng của ma trận N
print("\nc) Hạng của N =", np.linalg.matrix_rank(N))

a) M × N =
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b) Định thức M = 0.0

c) Hạng của N = 2
