In [1]:
import numpy as np
from numpy.linalg import det, matrix_rank
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# a) Tính tích ma trận M × N
product_MN = np.dot(M, N)

print("a) Tích ma trận M × N =\n", product_MN)

# b) Tính định thức của ma trận M
# Ma trận M là ma trận vuông (4x4) nên có thể tính định thức
det_M = det(M)

print("\nb) Định thức của ma trận M =", round(det_M, 3))

# c) Tính hạng của ma trận N
rank_N = matrix_rank(N)

print("\nc) Hạng của ma trận N =", rank_N)


a) Tích ma trận M × N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b) Định thức của ma trận M = 409.0

c) Hạng của ma trận N = 4
