In [1]:
import numpy as np
from numpy.linalg import norm
from math import degrees, acos
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([
    [2, -1, 3],
    [1, 4, -2],
    [0, 2, 5]
])

# a) Tính tổng A + B và tích số 2A + 3B
sum_AB = A + B
linear_combination = 2*A + 3*B

print("a)")
print("Tổng A + B =", sum_AB)
print("Tích số 2A + 3B =", linear_combination)

# b) Tích vô hướng A · B và góc giữa hai vector (độ)
dot_product = np.dot(A, B)
cos_theta = dot_product / (norm(A) * norm(B))
angle_degrees = round(degrees(acos(cos_theta)), 3)

print("\nb)")
print("Tích vô hướng A · B =", dot_product)
print("Góc giữa hai vector (độ) =", angle_degrees)

# c) Tính tích ma trận C nhân với chuyển vị của nó: C * C^T
product_C_CT = np.dot(C, C.T)

print("\nc)")
print("Tích ma trận C * C^T =\n", product_C_CT)


a)
Tổng A + B = [2 3 1 6]
Tích số 2A + 3B = [ 3 11  2 14]

b)
Tích vô hướng A · B = -5
Góc giữa hai vector (độ) = 99.594

c)
Tích ma trận C * C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]
