In [1]:
import numpy as np
from numpy.linalg import inv, LinAlgError

# a) Khởi tạo ma trận P
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

print("a)")

try:
    P_inv = inv(P)
    print("Ma trận nghịch đảo của P =\n", np.round(P_inv, 3))
except LinAlgError:
    print("Ma trận P không khả nghịch (định thức bằng 0).")

# b) Giải hệ phương trình: P * [x, y, z, w]^T = b
print("\nb)")
b = np.array([6, 8, 3, 7])
x = np.dot(P_inv, b)
print("Nghiệm của hệ phương trình [x, y, z, w] =\n", np.round(x, 3))

# c) Kiểm tra lại nghiệm
print("\nc)")
b_check = np.dot(P, x)
print("P * nghiệm =\n", np.round(b_check, 3))
print("Vector ban đầu b =\n", b)


a)
Ma trận nghịch đảo của P =
 [[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

b)
Nghiệm của hệ phương trình [x, y, z, w] =
 [2.    1.714 0.429 0.857]

c)
P * nghiệm =
 [6. 8. 3. 7.]
Vector ban đầu b =
 [6 8 3 7]
